<!-- IT21311086 
 Dharmadasa.P.S.K -->
 <!DOCTYPE html>
<html>
    <head>
        <style>
        .button {
            background-color: #f44336;
            color: white;
            padding: 14px 25px;
            text-align:center;
            text-decoration: none;
            display: inline-block;
          }
          
        </style>
    </head>
    <body>
	    <?php

    include('Header.php');

    ?>
        <link rel="Header" href="Header.php">
        <p><b>Top Employer</b></p>
        <form>
            <form>
                  <input type="radio" id="All" name="fav_language"  checked="checked" value="All">
                  <label for="All">All</label>
                  <input type="radio" id="Open with job" name="fav_language" value="Open with job">
                  <label for="Open with job">Open with job</label>
                  <input type="radio" id="By industry" name="fav_language" value="By industry">
                  <label for="By industry">By industry</label>
                 <input type="radio" id="Alphabetical" name="fav_language" value="Alphabetical">
                  <label for="Alphabetical">Alphabetical</label>
                </form> 
        </form>
        <a href="https://careers.microsoft.com/students/us/en/us-full-time-results">
        <img src="images/microsoft.jpg" width="300px" height="200px" >
         </a>
         <a href="https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/requisitions?location=United%20States&locationId=300000000149325">
        <img src="images/oracle.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.amazon.jobs/en/job_categories/software-development">
        <img src="images/Amazon.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.ibm.com/employment/">
        <img src="images/ibm.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.hdlcompanies.com/about/careers">
        <img src="images/DHL.png"  width="300px" height="200px">
        </a>
        <a href="www.takedajobs.com">
        <img src="images/taceda.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.toyota.com/usa/careers/">
        <img src="images/toyota.jpg" width="300px" height="200px">
        </a>
        <a href="https://www.tata.com/careers/jobs">
        <img src="images/TATA.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.combank.lk/careers">
        <img src="images/cBank.jpg"  width="300px" height="200px">
        </a>
        <a href="https://www.combank.lk/careers">
        <img src="images/mbank.png" width="300px" height="200px">
        </a>
        
          <br>
          <div class="button">
        <a href="" target="_blank">Back</a>
        <a href="" target="_blank">Next</a>
        <link rel="Footer" href="Footer.php">
    </div>
	
	<?php

    include('Footer.php');

    ?>
    </body>

</html>